### ISSUE TITLE
Inconsistency with Hi-C scaffolds vs. genetic map

### ISSUE THREAD

**Issue by peterdfields** [machinegun/SALSA#10]
I'm working with a dataset in which we have a relatively good genetic map derived from an F2 panel. It seems like the Hi-C is doing well in clustering contigs into scaffold groups that are consistent with linkage groups but within these groupings there can be quite a lot of disagreement. Is there a way to tinker with stringency parameters in order to determine what might be going wrong with the Hi-C scaffolding?

**Comment by machinegun** [comment]
In the file links_to_graph3.py, on line 123, there is a line 'count > 60'. If you increase this value, then you will get fragmented but more correct scaffolds. I would keep this value to the median of column 3 of new_links_sorted of the output. Also in new_links.py file, on line 58 and 59, you can change the value of l1 and l2. What it is indicating is that from how much regions from the end of the contig, you would like to consider the hic links. So if you increase this value then more links will be considered between two contigs but that would reduce the specificity. I would recommend to try editing the links_to_graph3.py file first.
