### ISSUE TITLE
Lots of missing data

### ISSUE THREAD

**Issue by mw55309** [machinegun/SALSA#13]
Hey

I think I need to figure out which params to adjust... I have 66 contigs, total length 1.8Mb

When I run SALSA, I end up with 3 scaffolds (YAY!) but with only 400kb length (boo!)

The AGP shows that each scaffold is a merging of two pairs of contigs (OK...) but the new_links_sorted file suggests there are 1938 unique links between contigs

These 3 pairs did have hundreds of links between them, but they were by no means the highest and other pairs had as high or higher number of links.

Any idea what might be happening?

Here is the AGP:

```sh
scaffold_1      1       62436   1       W       NODE_225_length_62436_cov_43.0636       1       62436   +
scaffold_1      62437   62936   2       N       500     scaffold        yes     na
scaffold_1      62937   171443  3       W       NODE_27_length_108507_cov_43.5609       1       108507  -
scaffold_1      171444  171943  4       N       500     scaffold        yes     na
scaffold_2      1       91316   1       W       NODE_59_length_91316_cov_42.7408        1       91316   +
scaffold_2      91317   91816   2       N       500     scaffold        yes     na
scaffold_2      91817   204445  3       W       NODE_25_length_112629_cov_42.9302       1       112629  -
scaffold_2      204446  204945  4       N       500     scaffold        yes     na
scaffold_3      1       56446   1       W       NODE_287_length_56446_cov_44.2677       1       56446   +
scaffold_3      56447   56946   2       N       500     scaffold        yes     na
scaffold_3      56947   89705   3       W       NODE_1218_length_32759_cov_43.2384      1       32759   -
scaffold_3      89706   90205   4       N       500     scaffold        yes     na
```

Here is the head of new_links_sorted

```sh
NODE_225_length_62436_cov_43.0636:E NODE_27_length_108507_cov_43.5609:E 3.0930812669 226
NODE_184_length_66629_cov_43.5219:E NODE_27_length_108507_cov_43.5609:E 3.05840488864 273
NODE_25_length_112629_cov_42.9302:E NODE_59_length_91316_cov_42.7408:E 3.04631625286 383
NODE_25_length_112629_cov_42.9302:E NODE_27_length_108507_cov_43.5609:E 2.79715011944 310
NODE_27_length_108507_cov_43.5609:E NODE_59_length_91316_cov_42.7408:E 2.57322847893 266
NODE_184_length_66629_cov_43.5219:E NODE_59_length_91316_cov_42.7408:E 2.32333197141 242
NODE_184_length_66629_cov_43.5219:E NODE_25_length_112629_cov_42.9302:E 2.26670520893 253
NODE_158_length_69544_cov_43.9225:E NODE_27_length_108507_cov_43.5609:E 2.12493864459 149
NODE_225_length_62436_cov_43.0636:E NODE_25_length_112629_cov_42.9302:E 1.80256030452 172
NODE_242_length_60045_cov_43.2957:E NODE_27_length_108507_cov_43.5609:E 1.78590949468 195
```

Cheers
Mick

**Comment by machinegun** [comment]
Hey Mick,

In the file linkstograph3.py, on line 142, you can change this `if count < 150:`. Currently, it would consider links only with hic links more than 150. 
Alternatively, you can take a look at the code in 'iterative salsa' branch. We have made some changes to the initial version of the code. In that code, you won't have to set any cutoffs.

Thanks,
Jay

**Comment by mw55309** [comment]
Thank you!

**Comment by mw55309** [comment]
So the iterative pipeline took my assembly from 66 contigs to 33 scaffolds.....

I still feel perhaps it is being too conservative, are there lines of code or params to adjust?

Also, I used two enzymes (S3 and M1), how important is it to specifiy this?

**Comment by machinegun** [comment]
Can you try running more iterations for iterative pipeline by setting -i
parameter?

About enzymes, it is used to score links. You can specify them while
running the script run_pipeline.py.

**Comment by mw55309** [comment]
OK that is better - I tried 35 iterations and got down to ~10 scaffolds

Is there a way of knowing where the optimum is?  

Related, what is the relation between the "nodes" and "edges" count in the output?  Should I run lots of iterations and choose the # of iterations that gives the lowest number of edges or nodes?

E.g. Another assembly, after one iteration had "nodes = 50 edges = 27" which seems good, but every iteration after that had more edges and nodes, finally settling on "nodes = 124 edges = 64"

Any help appreciated

Cheers
Mick

**Comment by machinegun** [comment]
We are still exploring on the appropriate stopping condition for scaffolding :). We don't have a definite answer for now about when to stop scaffolding. I would recommend following the approach you suggested in your response.
