### ISSUE TITLE
How to use the -t option?

### ISSUE THREAD

**Issue by billzt** [machinegun/SALSA#17]
```
-t TENX, --tenx TENX  10x links tab separated file, sorted by last columnls
```

I have 10X genomic data, but I did not know use to use this option. There are no manuals

**Comment by machinegun** [comment]
Actually, SALSA does not use 10x links for scaffolding. It was supposed to be an experimental option. I will update the source to make it clear. 

Sorry for the trouble.

**Comment by billzt** [comment]
Thanks. Well, I've alreay have 10X data, do you know which software can be used to deal them?

**Comment by machinegun** [comment]
You can use 10x genomics software (I think Supernova) to scaffold your
assemblies with 10x data first and then use SALSA  to scaffold with HiC.

**Comment by billzt** [comment]
Thank you. I'll have a try
