### ISSUE TITLE
scaffolds growing in each iteration 

### ISSUE THREAD

**Issue by MartinPippel** [machinegun/SALSA#19]
I have a pacbio vertebrate assembly (NgG50 4.5M) which was scaffolded with a two enzyme bionano hybrid scaffolding (NG50 28M). 
To get full chromosomes I applied SALSA with a 46x coverage HIC data set. And I did the Arima HiC
mapping approach.
The longest scaffold is growing in each iteration starting from 46M (1st iteration) to 228M in the final scaffold file. I also have a genetic map, that disagrees with all iterative joining steps for this scaffold. For the other scaffolds, the merging works quite well. 

Is it possible to run SALSA in a more conservative way?

**Comment by machinegun** [comment]
Did you try correcting the input assembly with SALSA's -m option? This would remove the errors in the input scaffolds/assembly which could propagate in each iteration. 

There is a way to run SALSA more conservatively. I will let you know once I push the changes to run it that way.

**Comment by MartinPippel** [comment]
I did this as well. And the largest scaffold is around 80M, which I think is still a bit high. 
Is it possible to some how trace back the original scaffold names? 

The input_breaks file is empty. But the scaffold_length_iteration_1 file has completely other names.

contig_46       3702134
contig_47       31721170
contig_44       22631765
...

I need to map them back to the original names:
>Super-Scaffold_1
>Super-Scaffold_2
>Super-Scaffold_3
...

**Comment by machinegun** [comment]
Hi,

If you pull the latest code, it would now map back scaffolds to the original contig names rather than the 'contig_*'.  That way from the agp file, you can track down which contigs from the assembly were scaffolded together.

**Comment by MartinPippel** [comment]
thanks.
