### ISSUE TITLE
When enabling "clean" mode with "-m yes", contig names are changed to "contig_#" by mistake?

### ISSUE THREAD

**Issue by sirasris** [machinegun/SALSA#22]
When enabling "clean" mode with "-m yes", contig names are changed to "contig_#". This causes mismatch between contig name in .bed data and in SALSA's output file.

Line 47 of correct.py should be: contig2newseq[seq] = input_seqs[seq]? 

https://github.com/machinegun/SALSA/blob/8b326ccd4456eb8479d75d44fda1f101cb7c2529/correct.py#L47

**Comment by machinegun** [comment]
Thanks a lot. I have fixed this bug.
