### ISSUE TITLE
How to generate the interaction picture after scaffolding?

### ISSUE THREAD

**Issue by yeswzc** [machinegun/SALSA#25]
Hi,
  How to generate the interaction picture after scaffolding?
  I want to ask is there file/files in the output available to make the interaction picture? Or do I need to align the HiC reads to the scaffold and then make the picture by my self?

**Comment by machinegun** [comment]
Hi,

Currently, we don't have a code to generate the interaction heatmap. You can use juicer to align reads to the scaffolds and then use the .hic file generated by juicer to visualize the heatmap in juicebox.

**Comment by yeswzc** [comment]
It's Ok. Thank you!
