### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by milkcookie** [machinegun/SALSA#27]
Hi all:
    when I run this protocol, I get a error:
bedfile loaded
Starting Iteration 1
bedfile started
bedfile loaded
Loading Hi-C links 
Finished loading Hi-C links, Loading unitig links now..
Hybrid scaffold graph loaded, nodes = 1268 edges = 1059
Hi-C implied edges = 0
Unitig tiling implied edges = 0
Assembly graph implied edges = 0
10x implied edges = 0
Traceback (most recent call last):
  File "/public1/home/stu_yanhansong/software/Hi-C/SALSA/layout_unitigs.py", line 1056, in <module>
    update_bed(expanded_scaffold_paths)
  File "/public1/home/stu_yanhansong/software/Hi-C/SALSA/layout_unitigs.py", line 801, in update_bed
    first = prev_attrs[3].split('/')[1]
IndexError: list index out of range
any suggestion?
thanks
FAFU
Hansong Yan

**Comment by milkcookie** [comment]
Hi:
    Thanks, I found the error, I use convert2bed --input=bam --output=bed to trans, so I get the wrong format bed file for SALSA, thanks reply me.

**Comment by Hannah1746** [comment]
I am running into the same problem but I am using the suggested converter:
bamToBed -i alignment.bam > alignment.bed
sort -k 4 alignment.bed > tmp && mv tmp alignment.bed

This is my Bed file.
450_pilon_pilon	940760	940902	000000c7-34de-440b-b140-074231d41472	24	-
4128_pilon_pilon	228690	228868	000000c7-34de-440b-b140-074231d41472	60	-
606_pilon_pilon	391471	391720	00000a31-ce1a-4023-b087-f02cf9889ab1	52	+
540_pilon_pilon	238382	238588	000016cf-096e-4fce-badc-a74c08f6af5b	0	+
