### ISSUE TITLE
How many times will the program iterate?

### ISSUE THREAD

**Issue by jhtrujillo** [machinegun/SALSA#29]
Hi!

I defined the maximum number of iterations with 3, but the program keeps iterating. When will it stop?

Thanks!

**Comment by machinegun** [comment]
Hi,

Did you set it is -i 3? How many iterations did it run for?

**Comment by jeanlain** [comment]
The script is also iterating past 3 here (currently iteration 8) and I haven't set the -i parameter. I don't have any issue with that, as long as it improves the assembly, but it doesn't look like the default number of iteration is 3, as opposed to what is said in the help. I the number of iteration automatically determined?

**Comment by machinegun** [comment]
Thanks for reporting this. I am working on fixing this issue. I will keep this issue open until I push the corrected code.
