### ISSUE TITLE
canu + salsa

### ISSUE THREAD

**Issue by ersgupta** [machinegun/SALSA#31]
Hi I am using salsa with assemblies generated by canu. Somehow salsa is exiting after 3 iterations when I used either of unitigs or contigs without any scaffolding. I read in another post you mention that is because salsa did not find any more links and probably it is due to the coverage of hic data.

I also ran salsa with a falcon assembly from same data and it ran for 16 iterations and increased longest scaffold from 3mb to 22mb.

I am not sure what exactly is the issue here. Any help please?

**Comment by machinegun** [comment]
Hi,
What's the input assembly n50 for Canu and Falcon? Also, what's the coverage for the Hi-C data?

**Comment by ersgupta** [comment]
N50 is 329kb (falcon) and 229kb (canu)
Hi-C data has 2 libraries: 95M + 80M read pairs (2*151)
Genome size: ~1.4gb, so coverage is ~38x

**Comment by machinegun** [comment]
Do you know the percentage of reads mapped to falcon and canu assembly?

**Comment by ersgupta** [comment]
Sorry for the late reply, I was waiting for phasing (separate haplotigs) the canu assembly to finish before using salsa. (Same result with phased canu assembly also)
I used ArimaGenomics guidelines to align and process the reads.

Number of reads after processing:
Falcon - 9M read pairs
Canu (primary assembly after separating the haplotigs) - 18M read pairs

Assembly size for falcon and canu was almost same.

As you can see the number of reads with canu assembly are almost double than falcon but still salsa scaffolding did not join the scaffolds for canu.

**Comment by ersgupta** [comment]
I have probably figured it out, after converting bam to bed, the bed file was not sorted by read names. now it works with significant increase in n50 and longest scaffolds.
