### ISSUE TITLE
-u option usage is not very clear

### ISSUE THREAD

**Issue by jeanlain** [machinegun/SALSA#33]
The -u option specifies "The tiling of unitigs to contigs in bed format"
But its use should be made more explicit. 
First, the guide should describe how this bed file is structured, as the bed format has optional fields Based on the bed format specs, I thought the format should be (in column order)

- contig name
- start coordinate of unitig in contig
- end coordinate of unitig in contig
- unitig name
- feature score (arbitrary?)
- orientation of unitig in contig

Is this correct?

Also, it's not very clear what the reference genome to map Hi-C reads onto must be in this case. Must Hi-C reads be mapped onto the contigs or onto the unitigs?

I am trying salsa with Hi-C reads mapped on unitigs and a tiling bed file specified as above. (I have also specified a gfa file generated during unitig assembly). The script is running, but the output says "Unitig tiling implied edges = 0" at each iteration, so I wonder if I did something wrong. 

Thanks.

**Comment by machinegun** [comment]
Hi,

-u option is very specific if you use asm.unitigs.fasta file generated by canu. So you should map Hi-C reads to unitigs first, run SALSA with these alignments (optionally with graph). Once you get scaffolds, you can use stitch.py script. It would merge unitigs based on tiling bed file. This would reduce the gaps in the scaffolds and potentially remove any duplicated sequence. I will make this clear in the documentation.
