### ISSUE TITLE
Is this SALSA or SALSA2? 

### ISSUE THREAD

**Issue by ShwethaMurali** [machinegun/SALSA#35]
Not an issue, just a question: I'm looking for SALSA2 from this preprint: https://www.biorxiv.org/content/early/2018/02/07/261149.full.pdf+html

**Comment by machinegun** [comment]
This is SALSA2. The previous SALSA is under a different branch. The master branch is for SALSA2 in the preprint you mentioned. 
Apologies for the confusion.

**Comment by ShwethaMurali** [comment]
Super! Thanks :)
