### ISSUE TITLE
How to get scaffold

### ISSUE THREAD

**Issue by fantasticair** [machinegun/SALSA#37]
Currently my data has **contigs.fasta , unitigs.fasta and HiC data** , and I got the **bam file** using the **https://github.com/ArimaGenomics method**.
Next, I ran python run_"**pipeline.py -a contigs.fasta -l contigs.fasta.fai -b alignment.bed -e {Your Enzyme} -o scaffolds** "and "**python run_pipeline.py -a contigs.fasta -l contigs.fasta .fai -b alignment.bed -e {Your Enzyme} -o scaffolds -m yes**".
Since there are no unitigs_graph.gfa and contigs_graph.gfa files I ran directly "**python stitch.py -c contigs.fasta -u unitigs.fasta -p scaffolds_iteration_x.p -o output_scaffolds.fasta**", and I got an error without getting output_scaffolds.fasta, error message Is "Traceback (most recent call last):
   File "/home/SALSA-master/stitch.py", line 46, in <module>
     With open(args.bed,'r') as f:
TypeError: coercing to Unicode: need string or buffer, NoneType found
”
Can you give me some suggestions?

**Comment by machinegun** [comment]
To stitch unitigs into contigs, you need the bed file describing the layout of unitigs along contigs. This is given by Canu assembler. Without this file, you can't stitch the sequences. 

One possible fix you can do is use mashmap or nucmer to align unitigs to contigs and obtain a layout in bed format and use that file to "stitch" unitigs into contigs, but I am not sure how well it would reduce the sequence duplication.

**Comment by fantasticair** [comment]
thank you!

**Comment by fantasticair** [comment]
I used the mashmap software to get the bed file describing the layout of unitigs along contigs，can you tell me that the SALSA software needs to enter the format of the bed file (what information is included with it)?
best wishes

**Comment by fantasticair** [comment]
I still have a question, is this start and end part of unitig or contig location information?Since the **### 

> https://github.com/marbl/MashMap

** output file contains the start and end of contig and unitig, I don't know which one to use.

**Comment by machinegun** [comment]
This is from the README file from mashmap:
```
The output is space-delimited with each line consisting of query name, length, 0-based start, end, strand, target name, length, start, end and mapping nucleotide identity.

```

You can extract the columns to obtain the start and end coordinates of the alignments.

**Comment by fantasticair** [comment]
thank you very much for your help,now i get the mashmap.out file ,the information inside is as
`utg6 2527761 0 1884999 + Contig00001 2670482 109 1998414 94.1462
utg6 2527761 1885000 1919999 + Contig00001 2670482 1992403 2026505 92.6938
utg6 2527761 1925000 2149999 + Contig00001 2670482 2035351 2273630 94.1892
utg6 2527761 2155000 2389999 + Contig00001 2670482 2280538 2523134 94.4045
utg6 2527761 2395000 2527760 + Contig00001 2670482 2530052 2670206 94.0402
utg6 2527761 2390000 2399999 + Contig00340 339642 67072 74090 82.9737
utg6 2527761 1920000 1924999 - Contig00632 913052 127321 132320 83.6565
utg6 2527761 2150000 2154999 + Contig00681 213093 152935 157934 85.864
utg14 474412 0 474411 + Contig00696 508394 220 508303 93.0056
utg17 81647 0 81646 + Contig01333 85806 8 85768 93.6288
`
I will  order by contig_id and for each contig id, the unitigs will be sorted by start coordinates.
but ,I don't know if  `start end` is contig or unitig's starting termination location information in the bed file.
`contig_id_1 start end unitig1
contig_id_2 start end unitig2`

**Comment by machinegun** [comment]
start and end are the coordinates in the contig (and not unitig).

**Comment by fantasticair** [comment]
hello
I have got the required bed file(unitigs_to_contig.bed) in the following format:

Contig00001     109     1998414 utg6
Contig00001     1992403 2026505 utg6
Contig00001     2035351 2273630 utg6
Contig00001     2280538 2523134 utg6
Contig00001     2530052 2670206 utg6
Contig00001     1779348 1784347 utg42
Contig00001     183582  203355  utg139

Since each contig may correspond to multiple unitigs in different areas, I have the following error when I run the `python2.7  /home/stitch.py  -c genome.fasta  -u unitig.fa -p scaffolds_iteration_1.p -b unitigs_to_contig.bed -o output_scaffolds.fasta` program.

Traceback (most recent call last):
  File "/home/stitch.py", line 173, in <module>
    scaffold_seq += unitig_seqs[utg]
KeyError: 'Contig01408'

**Comment by fantasticair** [comment]
hello,
I have reached the final step, but the above questions have not been resolved. Can you help me with some suggestions?

Best wishes

**Comment by machinegun** [comment]
Hi,

I have modified the stitch.py code and pushed it on github. It was assuming namings in Canu assembler style. Can you try to run now and see if it works?

**Comment by machinegun** [comment]
I am closing this issue for now. Please let me know if you encounter any problem with this in future.
