### ISSUE TITLE
Large discrepancies between versions within the last 30 days.

### ISSUE THREAD

**Issue by seanformby** [machinegun/SALSA#39]
Hi there,

First of all, I want to say say thank you for this program! Its pretty great!

However, I am having a lot of trouble with the discrepancy between the different updates within the last 25 days.  For my scaffolding, of the genome I working with.  I am getting differences between the N50 and largest scaffold size for the assemblies when using the latest code, code posted 10 days ago and code posted 25 days ago. I am not sure what to trust as to what is real.

For example, with the break code enable and and un-enabled..

I get the following.

TODAY: with break (-m yes)
sum = 131656186, n = 115, ave = 1144836.40, largest = 20897536
N50 = 3495147, n = 11

TODAY WITHOUT BREAK
sum = 131656186, n = 115, ave = 1144836.40, largest = 20897536
N50 = 3495147, n = 11

WITH BREAK 10 DAYS
sum = 131659186, n = 109, ave = 1207882.44, largest = 16599318
N50 = 4168397, n = 10

WITHOUTBREAK 10 DAYS 
sum = 131659186, n = 109, ave = 1207882.44, largest = 16599318
N50 = 4168397, n = 10

WITH BREAK 30 DAYS
sum = 131649371, n = 101, ave = 1303459.12, largest = 46276934
N50 = 5032004, n = 4

WITHOUTBREAK 30 DAYS 
sum = 131637371, n = 115, ave = 1144672.79, largest = 28565372
N50 = 4576694, n = 8

I am just not sure what update to trust. The latest? Or the previosus?

Thanks for all the help!

**Comment by machinegun** [comment]
Hi,

We are constantly improving the software so that's why you might see different results. We have updated the misjoin detection strategy and is implemented in the latest version.  I would recommend using the latest version for your analysis.
