### ISSUE TITLE
mapping example

### ISSUE THREAD

**Issue by mictadlo** [machinegun/SALSA#41]
Hi,
I have the following Hi-C data

```
> ls -1
N_Ben_HiC2.R1.fq.gz
N_Ben_HiC2.R2.fq.gz
N_Ben_HiC4.R1.fq.gz
N_Ben_HiC4.R2.fq.gz
```
How to align all the above files with ArimaGenomics pipeline (I have also asked [here](https://github.com/ArimaGenomics/mapping_pipeline/issues/2)) or do you recommend something different?
Do I have to change the filenames?
Will ArimaGenomics recognize all of my 4 files and align them in one go?

Thank you in advance.

Michal

**Comment by machinegun** [comment]
I don't know of the mapping pipeline has a default way to use multiple
libraries. One quick hack can be combining all R1 files into one and R2
file into other, and use them as an input to the mapping pipeline.
Alternatively, you can run mapping pipeline independently on both the
libraries and then merge the bam files using samtools.

**Comment by mictadlo** [comment]
Does your software require Read Groups?

**Comment by machinegun** [comment]
No

**Comment by mictadlo** [comment]
Hi, 
I had to run the multiple libraries separately through ArimaGenomics' pipeline. Afterward ,I merged the two bam files together with samtools merge.

ArimaGenomics' pipeline creates Read Groups.

Michal
