### ISSUE TITLE
chromosomes in seperated FASTA file

### ISSUE THREAD

**Issue by mictadlo** [machinegun/SALSA#43]
Hi,
How do I get after SALSA for each chromosome a separated FASTA file?

Thank you in advance.

Michal

**Comment by machinegun** [comment]
Currently, we don't provide chromosome-wise FASTA file. However, if you need to extract chromosomes, the sequences in `scaffolds_FINAL.fasta` file are ordered by their length in decreasing order. So if you expect 10 chromosomes, you can just extract the first 10 sequences from that file.

**Comment by mictadlo** [comment]
Hi, 
But the salsa output contains around 5000 scaffolds. How can I group them?

Thank you in advance?

Michal

**Comment by machinegun** [comment]
SALSA groups as many contigs as it can into chromosomes. Can you tell what's the N50 of input contigs and scaffolds? That would give a better idea about how much scaffolding has actually happened.

**Comment by mictadlo** [comment]
Hi,

```
dbg2olc-40x> abyss-fac pilon/pilon.fasta
n	n:500	L50	min	N75	N50	N25	E-size	max	sum	name
15076	15076	2175	1139	225881	422976	709950	524856	2716690	3.055e9	pilon/pilon.fasta

dbg2olc-40x> python /work/waterhouse_team/apps/SALSA/run_pipeline.py -a pilon/pilon.fasta -l pilon/pilon.fasta.fai -b hic-bams-paired-dedup-merge/all.hic.sorted.dedup.bed -e GATC -o salsa -m yes

dbg2olc-40x> abyss-fac salsa/scaffolds_FINAL.fasta 
n	n:500	L50	min	N75	N50	N25	E-size	max	sum	name
7301	7301	116	1139	3338348	7295569	13.77e6	10.21e6	54.72e6	3.055e9	salsa/scaffolds_FINAL.fasta
```

Thank you in advance,

Michal

**Comment by machinegun** [comment]
Is this a genome with a known reference? If yes, what's the reference N50? When you sort sequences in decreasing order of lengths, how many sequences consist of 90% (or 95%) of the assembly length? That can give you the idea of chromosome sizes if the reference is not known.

**Comment by mictadlo** [comment]
There is only an Illumina based draft genome without HI-C. The assembly used for SALSA is based on a hybrid assembly (SparseAssembler + DBG2OLC + Racon + Pilon). 

Do you have any commands for your above methods?

Thank you in advance.

Michal

**Comment by machinegun** [comment]
I am not sure about the assembly methods. Maybe @skoren can tell you if that's the best way to go.
