### ISSUE TITLE
layout_unitigs.py Key Error

### ISSUE THREAD

**Issue by rwhetten** [machinegun/SALSA#45]
I'm running  the program in a python 2.7 virtualenv on a cluster, and it produces initial output to STDERR that seems promising:
bedfile loaded
Starting Iteration 1
Loading Hi-C links 
Finished loading Hi-C links, Loading unitig links now..
Hybrid scaffold graph loaded, nodes = 0 edges = 0
Hi-C implied edges = 0
Unitig tiling implied edges = 0
Assembly graph implied edges = 0
10x implied edges = 0
After this point the output directory contains files called assembly_cleaned.fasta, commands.log, scaffolds_iteration_1.p, and scaffold_length_iteration_1 with non-zero sizes, as well as several others with size 0. Shortly after that point, though, the job fails with exit code 1, and the error output contains the messages
 Traceback (most recent call last):
  File "/home/rwhetten/tools/SALSA-2.0/layout_unitigs.py", line 1056, in <module>
    update_bed(expanded_scaffold_paths)
  File "/home/rwhetten/tools/SALSA-2.0/layout_unitigs.py", line 752, in update_bed
    scaffold_re[key] = re_counts[contig]
KeyError: 'contig_12719214'
Grep finds a sequence with the header line >contig_12719214 in the assembly_cleaned.fasta file, but the sequence is very short (<100 nt) and does not contain a recognition site for the enzyme used to prepare the HiC library. Should the reference genome sequence file be filtered to remove short contigs and those without restriction enzyme recognition sites before running SALSA2?

**Comment by rwhetten** [comment]
Update - I ran the pipeline again, including the options  -c 30000 nt, -m yes, and -e GATC (which I inadvertently left out for the first run, above). The second run also failed, at a different step, but similar circumstances. The error file contains:
 bedfile loaded
Starting Iteration 1
Traceback (most recent call last):
  File "/home/rwhetten/tools/SALSA-2.0/refactor_breaks.py", line 241, in <module>
    update_bed(scaffolds_new)
  File "/home/rwhetten/tools/SALSA-2.0/refactor_breaks.py", line 72, in update_bed
    scaffold_re[key] = re_counts[contig]
KeyError: 'contig_9903214'

Again, this contig is present in the assembly.cleaned.fasta file in the output directory, but is short.
>contig_9903214
CAAAAACCTCTTCTTTATTATATGATTAATCTGTTTTGCATTTAATTCCATAATACTCTTATATTTTATCAGTTGAAGCG
Clearly the -c option does not prevent this problem. I will try subsetting the bed file to include only reads mapped to scaffolds >30 kb in length, then extracting the FASTA-format reference sequences for those scaffolds from the reference assembly, and test the pipeline with that subset of the data.

**Comment by ViriatoII** [comment]
This is an interesting question. 
I don't have your error messages (I'm using the default -c value), but I believe that many of my considered contigs are not mapped to by any HiC reads, causing SALSA to stop. 

Did you try removing those contigs from the assembly? Any results?

**Comment by rwhetten** [comment]
No, I have not yet tried removing short contigs from the bed file and the reference assembly, so I don't know if that will make a difference with this error.

**Comment by ViriatoII** [comment]
Now I found the same error as you did. This happened when I tried running SALSA against a version of reference to which the HiC reads were not mapped. Did you somehow do this?

The solution was redoing the whole mapping process to that new reference alignment.  

Hope  this helps, cheers.

**Comment by cmonat** [comment]
Hi,

I have a similar error but a little bit different.
For me the error is happening while loading the Hi-C data:

`bedfile loaded
Starting Iteration 1
python /opt/apps/salsa/SALSA-2.2/fast_scaled_scores.py -d scaffolds -i 1
sort -k 5 -gr scaffolds/contig_links_scaled_iteration_1 > scaffolds/contig_links_scaled_sorted_iteration_1
python /opt/apps/salsa/SALSA-2.2/layout_unitigs.py -x abc -l scaffolds/contig_links_scaled_sorted_iteration_1 -c 1000 -i 1 -d scaffolds
Loading Hi-C links
Traceback (most recent call last):
  File "/opt/apps/salsa/SALSA-2.2/layout_unitigs.py", line 929, in <module>
    generate_scaffold_graph()
  File "/opt/apps/salsa/SALSA-2.2/layout_unitigs.py", line 392, in generate_scaffold_graph
    if contig_length[c1] <= int(args.cutoff) or contig_length[c2] <= int(args.cutoff):
KeyError: 'ctg4633_2'`

Knowing I have launched the SALSA pipeline with the following command line:

`python /opt/apps/salsa/SALSA-2.2/run_pipeline.py -a /home/cmonat/WheatOMICS/Renan_rawont_v4.fasta -l /home/cmonat/WheatOMICS/Renan_rawont_v4.fasta.fai -b DEDUPLICATESfiles/SL1810052_merged.bed -e GATC,AATC,ATTC,ACTC,AGTC -o scaffolds -m yes`

Do you have any idea what I should do to correct this? Maybe I should not run the 4 ligations sites in the same pipeline? So far I have used the mapping_pipeline offered by Arima genomics (https://github.com/ArimaGenomics/mapping_pipeline) to map the Hi-C data to my sequences.

I hope everything is clear enough and that I provided all the information you need to help me.
Thank you very much in advance.
Cheers

C.
