### ISSUE TITLE
heatmap using SALSA result

### ISSUE THREAD

**Issue by wangxinbio** [machinegun/SALSA#46]
Hi 
Can I generate a heatmap using the SALSA result? Which file I need prepare?

Thanks
Xin

**Comment by machinegun** [comment]
You can use Juicebox or HiGlass to generate heatmap for SALSA result. SALSA doesn't support heatmap output, so you need to align the reads to the scaffolds in order to generate the heatmap.

**Comment by wangxinbio** [comment]
@machinegun Thanks for your response.
