### ISSUE TITLE
multiple libraries with different motifs

### ISSUE THREAD

**Issue by mcshane** [machinegun/SALSA#47]
If I have two libraries for one sample, one from Arima (`motif=GATC,GANTC`) and one from Dovetail (`motif=GATC`), can give both sets to SALSA in one run (combine the bed files as input to SALSA and set `motif=GATC,GANTC`), or would it be better to run serially?

**Comment by machinegun** [comment]
I think it would be better if you can provide information about both the libraries at once to SALSA. You could do the following to use both libs simultaneously:

1. First, concat the bed files for different libs and make it into a single bed file.
2. Count the number of restriction sites for GATC, and GANTC in first and second of half (0-length/2, length/2-length) of the contigs. (Make sure you count GATC twice as it's in both the libs). This file would have format as `contig_name #sites_in_first_half #sites_in_second_half`. 
3. Name this file as `re_counts_iteration_1` and move it to the output folder you provide to SALSA (`-o` option).
4. After you do this, run SALSA in a regular manner. It would not compute restriction sites as this file will already be present. 

Hopefully, this would work. Please let me know if you get stuck in the process.

**Comment by mcshane** [comment]
Thanks @machinegun. That makes sense and seems have worked. Well, it has at least run through. Result has a lower N50 than one of the libraries by itself, will have to look further at some of the joins to see which more correct.
