### ISSUE TITLE
Intrepreting misassembly output: count misassemblies

### ISSUE THREAD

**Issue by ViriatoII** [machinegun/SALSA#49]
Hey,

This is a short question. How do we interpret the misassembly outputs? 

If I want to count the **number of detected misassemblies**, do I count the number of total number of joins, the number of suspicious joins, or the number of scaffolds listed? 

 And are these numbers cumulative in iterations or should I add them to have the final misassembly number?

Cheers,
Ricardo

>-rwxrwx--- 1 guerreiro grp_stich          0 Nov 22 10:34 misasm_2.DONE*
-rwxrwx--- 1 guerreiro grp_stich          0 Nov 22 11:04 misasm_3.DONE*
-rwxrwx--- 1 guerreiro grp_stich        339 Nov 22 11:04 misasm_3.log*
-rwxrwx--- 1 guerreiro grp_stich          0 Nov 22 11:34 misasm_4.DONE*
-rwxrwx--- 1 guerreiro grp_stich       1569 Nov 22 11:34 misasm_4.log*
-rwxrwx--- 1 guerreiro grp_stich          0 Nov 22 12:03 misasm_5.DONE*
-rwxrwx--- 1 guerreiro grp_stich       3417 Nov 22 12:03 misasm_5.log*
-rwxrwx--- 1 guerreiro grp_stich       3166 Nov 22 10:27 misasm_iteration_2.report*
-rwxrwx--- 1 guerreiro grp_stich       3179 Nov 22 10:57 misasm_iteration_3.report*
-rwxrwx--- 1 guerreiro grp_stich       2949 Nov 22 11:27 misasm_iteration_4.report*
-rwxrwx--- 1 guerreiro grp_stich       2563 Nov 22 11:56 misasm_iteration_5.report*

tail misasm_iteration_2.report
>scaffold_171
scaffold_5684        #Or maybe I have to count the number of scaffolds that are listed here?
scaffold_2227
scaffold_1463
scaffold_5450
scaffold_517
scaffold_2751
Total Joins = 16
Suspicious Joins = 4
Percent Suspicious Joins = 25

tail  misasm_3.log 
>first part : ['scaffold43|size1912476:E', 'scaffold43|size1912476:B', 'scaffold231|size1220199_2:E', 'scaffold231|size1220199_2:B']
second part : ['scaffold397|size522461:B', 'scaffold397|size522461:E', 'scaffold106|size1423362:B', 'scaffold106|size1423362:E', 'scaffold440|size435153:B', 'scaffold440|size435153:E']

**Comment by davidries84** [comment]
Hi Ricardo,
maybe this can help:
From the manual: https://github.com/machinegun/SALSA#how-to-interpret-the-output

> SALSA generates a bunch of files in the output folder. SALSA is an iterative algorithm, so it generates files for each iteration. The files you will be interested in are scaffolds_FINAL.fasta, which contains the sequences for the scaffolds generated by the algorithm.

So I guess the results are already accumulated the "FINAL" files.

Best,
David

**Comment by ViriatoII** [comment]
Hey David,

There are 2 FINAL files:
>-rwxrwx--- 1 guerreiro grp_stich 1,2M Nov 23 16:05 scaffolds_FINAL.agp*
-rwxrwx--- 1 guerreiro grp_stich 1,1G Nov 23 16:05 scaffolds_FINAL.fasta*

The fasta file has obviously no information besides the fasta sequences.  And the agp file is like this:
>scaffold_1	1	2572653	1	W	scaffold36|size2572653	1	2572653	-	
scaffold_1	2572654	2573153	2	N	500	scaffold	yes	na
scaffold_1	2573154	9745708	3	W	scaffold3|size7172555	1	7172555	+	
scaffold_1	9745709	9746208	4	N	500	scaffold	yes	na
scaffold_1	9746209	10974638	5	W	scaffold156|size1228430	1	1228430	-	
scaffold_1	10974639	10975138	6	N	500	scaffold	yes	na
(more 19950 lines)

I still don't see how to count the detected misassemblies. It should be simple..

**Comment by machinegun** [comment]
If you just want to find the number of misjoins in the input assembly, you could do `wc -l input_breaks`. It also has the locations for misjoins.

**Comment by ViriatoII** [comment]
That's it, machinegun, thank you!

head input_breaks
>scaffold187     638329
scaffold171   	   938034
scaffold161	   630838
