### ISSUE TITLE
correct_links aborted:  Assertion `(std::size_t)i < pm.n' failed.

### ISSUE THREAD

**Issue by Tierhon** [machinegun/SALSA#50]
Hi,
I am running SALSA on a GFA created by Flye when correct_links crashes. Stderr:
`bedfile loaded
Starting Iteration 1
bedfile started
bedfile loaded
Done loading GFA file
Number of Nodes = 27928
Number of Edges = 461997442
correct_links: /usit/abel/u1/olekto/miniconda2/include/boost/graph/two_bit_color_map.hpp:86: void boost::put(const boost::two_bit_color_map<IndexMap>&, typename boost::property_traits<PMap>::key_type, boost::two_bit_color_type) [with IndexMap = boost::vec_adj_list_vertex_id_map<boost::property<boost::vertex_name_t, std::__cxx11::basic_string<char> >, long unsigned int>; typename boost::property_traits<PMap>::key_type = long unsigned int]: Assertion `(std::size_t)i < pm.n' failed.
/bin/sh: line 1: 85700 Aborted                 (core dumped) /projects/cees/bin/SALSA/correct_links -g 
assembly_graph.gfa -l scaffolds/contig_links_scaled_sorted_iteration_1 > scaffolds/tmp.links`

This is the output of stderr:
`python /path/RE_sites.py -a scaffolds/assembly.cleaned.fasta -e GATC > scaffolds/re_counts_iteration_1
python /path/make_links.py -b scaffolds/alignment_iteration_1.bed -d scaffolds -i 1 -x abc
python /pathfast_scaled_scores.py -d scaffolds -i 1
sort -k 5 -gr scaffolds/contig_links_scaled_iteration_1 > scaffolds/contig_links_scaled_sorted_iteration_1
`

Do you know what the issue might be? How many edges could I expect? 

Thank you. 

Ole

**Comment by machinegun** [comment]
I don't know if Flye graph is similar to the GFA output by CANU. Will look into it to see what's the difference between these two graphs.

**Comment by Tierhon** [comment]
Great, thank you. I am wondering if it is because of a large number of edges:

> Done loading GFA file
> Number of Nodes = 27928
> Number of Edges = 461997442

Another run with much less edges ran just fine. 

> Done loading GFA file
> Number of Nodes = 22308
> Number of Edges = 45130744

**Comment by dottorscaglione** [comment]
I have the same issue too. 

`Done loading GFA file
Number of Nodes = 70178
Number of Edges = 9192
correct_links: /mnt/vol1/projects/novabreed/share/mvidotto/bioinfotree/binary/appliedgenomics/local/stow/boost-1.55.0/include/boost/graph/two_bit_color_map.hpp:86: void boost::put(const boost::two_bit_color_map<IndexMap>&, typename boost::property_traits<PMap>::key_type, boost::two_bit_color_type) [with IndexMap = boost::vec_adj_list_vertex_id_map<boost::property<boost::vertex_name_t, std::basic_string<char> >, long unsigned int>; typename boost::property_traits<PMap>::key_type = long unsigned int]: Assertion (std::size_t)i < pm.n' failed.
/bin/sh: line 1: 138225 Aborted                 (core dumped) /mnt/vol1/projects/novabreed/share/bdubay/bin/SALSA-master/correct_links ......`

However  I notice that if I downsample to just 1M reads (the BED file), it runs till the end, it breaks when I start moving to 10M reads. The same 1M dataset however break again if trying to run with "-m no"...

Tried a couple of boost versions and it does not change behavior.

**Comment by machinegun** [comment]
Yeah, SALSA is mainly designed for long read assembly which usually doesn't have a large number of contigs/nodes. I am not sure if it's the issue with the boost version.
