### ISSUE TITLE
Running Time

### ISSUE THREAD

**Issue by Lcornet** [machinegun/SALSA#51]
Hello,

I am running SALSA on a Flye (https://github.com/fenderglass/Flye) assembly and it is in the Iteration 1 since 3 days : 
##
bedfile loaded
Starting Iteration 1
bedfile started
bedfile loaded
Done loading GFA file
Number of Nodes = 49542
Number of Edges = 2255685850
##

Is there anyway to know the remaining time of analysis ? Do i made something wrong in my pipeline ?

#bwa index scaffolds.fasta
#samtools faidx scaffolds.fasta
#bwa mem -t40 -SPM scaffolds.fasta 20160711.A-60444_HiC_R1.fastq.gz 20160711.A-60444_HiC_R2.fastq.gz > hic.sam
#samtools view -Sb hic.sam > hic-samtools.bam
#bamToBed -i hic-samtools.bam > hic-samtools.bed
#sort -k 4 hic-samtools.bed > tmp && mv tmp hic-samtools.bed
#python /media/vol1/apps/SALSA/run_pipeline.py -a scaffolds.fasta -l scaffolds.fasta.fai -b hic-samtools.bed -e GCTCTTCN  -o salsa1 -m yes -g assembly_graph.gfa

Thanks,
Luc

**Comment by machinegun** [comment]
The graph looks pretty dense with a lot of edges. I would try running it without the -g parameter.
