### ISSUE TITLE
GFA file loaded with Nodes = 0 and Edges = 0

### ISSUE THREAD

**Issue by nadegeguiglielmoni** [machinegun/SALSA#53]
I have used SALSA before with GFA file, and it seemed like it worked properly.

This time I used SALSA with a idba_ud assembly and the GFA file obtained with the script IDBA-to-GFA. 

I get the following : 

('/home/nadege/meta_romania/salsa_scaffolding_AATT_idba_with_gfa/salsa_scaffolding_idba_with_gfa.alignment.bed', '/home/nadege/meta_romania/salsa_scaffolding_AATT_idba_with_gfa/scaffolds/alignment_iteration_1.bed')
('/home/nadege/meta_romania/salsa_scaffolding_AATT_idba_with_gfa/salsa_scaffolding_idba_with_gfa.alignment.bed', '/home/nadege/meta_romania/salsa_scaffolding_AATT_idba_with_gfa/scaffolds/alignment_iteration_1.bed')
bedfile loaded
python /home/nadege/SALSA/RE_sites.py -a /home/nadege/meta_romania/salsa_scaffolding_AATT_idba_with_gfa/scaffolds/assembly.cleaned.fasta -e AATT > /home/nadege/meta_romania/salsa_scaffolding_AATT_idba_with_gfa/scaffolds/re_counts_iteration_1
Starting Iteration 1
python /home/nadege/SALSA/make_links.py -b /home/nadege/meta_romania/salsa_scaffolding_AATT_idba_with_gfa/scaffolds/alignment_iteration_1.bed -d /home/nadege/meta_romania/salsa_scaffolding_AATT_idba_with_gfa/scaffolds -i 1 -x abc
bedfile started
bedfile loaded
python /home/nadege/SALSA/fast_scaled_scores.py -d /home/nadege/meta_romania/salsa_scaffolding_AATT_idba_with_gfa/scaffolds -i 1
sort -k 5 -gr /home/nadege/meta_romania/salsa_scaffolding_AATT_idba_with_gfa/scaffolds/contig_links_scaled_iteration_1 > /home/nadege/meta_romania/salsa_scaffolding_AATT_idba_with_gfa/scaffolds/contig_links_scaled_sorted_iteration_1
Done loading GFA file
Number of Nodes = 0
Number of Edges = 0
python /home/nadege/SALSA/layout_unitigs.py -x /home/nadege/meta_romania/contig-100.gfa -l /home/nadege/meta_romania/salsa_scaffolding_AATT_idba_with_gfa/scaffolds/contig_links_scaled_sorted_iteration_1 -c 1000 -i 1 -d /home/nadege/meta_romania/salsa_scaffolding_AATT_idba_with_gfa/scaffolds
Loading Hi-C links 
Hybrid scaffold graph loaded, nodes = 876 edges = 626
Hi-C implied edges = 0

So it says that the GFA is loaded, but with Nodes = 0 and Edges = 0, which I then understand as the GFA not being loaded properly? What I find even more surprising is that I get different outputs with and without the GFA.

**Comment by machinegun** [comment]
Hi,

Can you please post the command you used to run SALSA?

**Comment by nadegeguiglielmoni** [comment]
The command line was : 

`python run_pipeline.py -a /home/nadege/meta_romania/salsa_scaffolding_AATT_idba_with_gfa/bwa_index/salsa_scaffolding_idba_with_gfa.fa -l /home/nadege/meta_romania/salsa_scaffolding_AATT_idba_with_gfa/bwa_index/salsa_scaffolding_idba_with_gfa.fa.fai -b /home/nadege/meta_romania/salsa_scaffolding_AATT_idba_with_gfa/salsa_scaffolding_idba_with_gfa.alignment.bed -e AATT -o /home/nadege/meta_romania/salsa_scaffolding_AATT_idba_with_gfa/scaffolds -m yes -c 1000 -g /home/nadege/meta_romania/contig-100.gfa`

**Comment by machinegun** [comment]
I am not sure what's the issue. Have you made sure the id's of contigs in gfa and fasta files ar identical?
