### ISSUE TITLE
unexpected stop at  Iteration  2

### ISSUE THREAD

**Issue by njaupan** [machinegun/SALSA#56]
Hi,
I have met the same problem like #38 but I put enzyme sequences (DnpII: GATC) but it stoped after iterature 2 and no scaffold generated:
$python ~/Downloads/software/SALSA/run_pipeline.py -a canu.fasta -l  canu.fasta.fai -b  merged.reduplicate.bam.sort.bed  -e GATC -m yes -o scaffolds
bedfile loaded
python /home/panpan/Downloads/software/SALSA/RE_sites.py -a scaffolds/assembly.cleaned.fasta -e GATC > scaffolds/re_counts_iteration_1
Starting Iteration 1
python /home/panpan/Downloads/software/SALSA/make_links.py -b scaffolds/alignment_iteration_1.bed -d scaffolds -i 1 -x abc
bedfile started
bedfile loaded
python /home/panpan/Downloads/software/SALSA/fast_scaled_scores.py -d scaffolds -i 1
sort -k 5 -gr scaffolds/contig_links_scaled_iteration_1 > scaffolds/contig_links_scaled_sorted_iteration_1
python /home/panpan/Downloads/software/SALSA/layout_unitigs.py -x abc -l scaffolds/contig_links_scaled_sorted_iteration_1 -c 1000 -i 1 -d scaffolds
Loading Hi-C links 
Hybrid scaffold graph loaded, nodes = 970 edges = 531
Hi-C implied edges = 0
/home/panpan/Downloads/software/SALSA/break_contigs -a scaffolds/alignment_iteration_2.bed -b scaffolds/breakpoints_iteration_2.txt -l scaffolds/scaffold_length_iteration_2 -i 2 -s 100   > scaffolds/misasm_iteration_2.report
python /home/panpan/Downloads/software/SALSA/refactor_breaks.py -d scaffolds -i 2
Starting Iteration 2
python /home/panpan/Downloads/software/SALSA/make_links.py -b scaffolds/alignment_iteration_2.bed -d scaffolds -i 2
bedfile started
bedfile loaded
Starting Iteration 2
$
Do you have anu suggestion? I have attached command log
Best,
panpan

[commands.log](https://github.com/machinegun/SALSA/files/2778644/commands.log)

**Comment by christinawu2008** [comment]
Hi, I don't see any error messages. Can you try it on a large memory machine?
