### ISSUE TITLE
I want to ask a question

### ISSUE THREAD

**Issue by zhangxiner2** [machinegun/SALSA#57]
Hello,
I meet a question when using the software . my command line likes this :
python2 ./run_pipeline.py -a ONTmin.fasta -l ONTmin.fasta.fai -b ONT.sort.REduced.paired_only.bed -e {AAGCTT} -o scaffolds
But the processing is stop without generate a new scaffold.The error is :
Starting Iteration 1
bedfile started
Traceback (most recent call last):
  File "/data/mg1/zhangx/nanopore/DATA/hic_test/salsa_hic/test/Lachesis_salsa/make_links.py", line 179, in <module>
    main()
  File "/data/mg1/zhangx/nanopore/DATA/hic_test/salsa_hic/test/Lachesis_salsa/make_links.py", line 112, in main
    norm_score[key] = RF_counts_left[first]*r1 + RF_counts_left[second]*r2
KeyError: 'utg000033l_pilon_pilon'

I would appreciate it if you answer me as soon as possible.

                                                              Xin

**Comment by christinawu2008** [comment]
Not sure which version you are using. But I recently tested SALSA2 and it works fine. Maybe you should try the module installed on powerplant by:

>module load salsa
>run_pipeline.py -a ONTmin.fasta -l ONTmin.fasta.fai -b ONT.sort.REduced.paired_only.bed -e {AAGCTT} -o scaffolds

**Comment by zhangxiner2** [comment]
So glad for receiving your reply. This problem has been solved but it stoped after iterature 2 and no scaffold generated like #56. The log like this:
bedfile loaded
Starting Iteration 1
bedfile started
bedfile loaded
Loading Hi-C links
Hybrid scaffold graph loaded, nodes = 11134 edges = 5567
Hi-C implied edges = 0
Starting Iteration 2
bedfile started
bedfile loaded
Starting Iteration 2

The attached command log like this:
/data/mg1/zhangx/eryuelan_nanopore/DATA/hic_test/salsa_hic/test/Lachesis_salsa/break_contigs_start -a scaffolds22/alignment_iteration_1.bed -l scaffolds22/scaffold_length_iteration_1 > scaffolds22/input_breaks -s 100python2 /data/mg1/zhangx/eryuelan_nanopore/DATA/hic_test/salsa_hic/test/Lachesis_salsa/correct.py  ONTmin_IT6.fasta scaffolds22/input_breaks scaffolds22/alignment_iteration_1.bed scaffolds22python2 /data/mg1/zhangx/eryuelan_nanopore/DATA/hic_test/salsa_hic/test/Lachesis_salsa/RE_sites.py -a scaffolds22/assembly.cleaned.fasta -e {AAGCTT} > scaffolds22/re_counts_iteration_1
python2 /data/mg1/zhangx/eryuelan_nanopore/DATA/hic_test/salsa_hic/test/Lachesis_salsa/make_links.py -b scaffolds22/alignment_iteration_1.bed -d scaffolds22 -i 1 -x abc
python2 /data/mg1/zhangx/eryuelan_nanopore/DATA/hic_test/salsa_hic/test/Lachesis_salsa/fast_scaled_scores.py -d scaffolds22 -i 1
sort -k 5 -gr scaffolds22/contig_links_scaled_iteration_1 > scaffolds22/contig_links_scaled_sorted_iteration_1
python2 /data/mg1/zhangx/eryuelan_nanopore/DATA/hic_test/salsa_hic/test/Lachesis_salsa/layout_unitigs.py -x abc -l scaffolds22/contig_links_scaled_sorted_iteration_1 -c 1000 -i 1 -d scaffolds22
/data/mg1/zhangx/eryuelan_nanopore/DATA/hic_test/salsa_hic/test/Lachesis_salsa/break_contigs -a scaffolds22/alignment_iteration_2.bed -b scaffolds22/breakpoints_iteration_2.txt -l scaffolds22/scaffold_length_iteration_2 -i 2 -s 100   > scaffolds22/misasm_iteration_2.report
python2 /data/mg1/zhangx/eryuelan_nanopore/DATA/hic_test/salsa_hic/test/Lachesis_salsa/refactor_breaks.py -d scaffolds22 -i 2
python2 /data/mg1/zhangx/eryuelan_nanopore/DATA/hic_test/salsa_hic/test/Lachesis_salsa/make_links.py -b scaffolds22/alignment_iteration_2.bed -d scaffolds22 -i 2
python2 /data/mg1/zhangx/eryuelan_nanopore/DATA/hic_test/salsa_hic/test/Lachesis_salsa/fast_scaled_scores.py -d scaffolds22 -i 2
sort -k 5 -gr scaffolds22/contig_links_scaled_iteration_2 > scaffolds22/contig_links_scaled_sorted_iteration_2

Do you have any suggestion? 
Best
Xin

**Comment by christinawu2008** [comment]
Hi, I don't see any error messages. Can you try it on a large memory machine?

**Comment by ViriatoII** [comment]
I have run SALSA several times successfully 2 months ago. Now, however, when I try to run the same scripts, I am faced with the same error as you

>python2 Scaffolding/SALSA/make_links.py -b it4_SSPAGE/SALSA_4_iterations/alignment_iteration_1.bed -d it4_SSPAGE/SALSA_4_iterations -i 1 -x abc
bedfile started
Traceback (most recent call last):
  File "/netscratch/irg/grp_stich/C34_PS/Scaffolding/SALSA/make_links.py", line 179, in <module>
    main()
  File "/netscratch/irg/grp_stich/C34_PS/Scaffolding/SALSA/make_links.py", line 136, in main
    norm_score[key] = RF_counts_right[first]*r1 + RF_counts_right[second]*r2
KeyError: 'scaffold2|size10448646_1'

**Comment by nadegeguiglielmoni** [comment]
The program stops abruptly because it does not find useful information in the file contig_links_scaled_sorted_iteration_1, therefore it uses 'break'. The problem with 'break' is that it stops as if nothing was wrong and it does not give you further information. I am not sure of why your contig_links_scaled_sorted_iteration_1 file would not provide useful links, but I think the origin might come from the quality of the processed Hi-C reads (or maybe a problem in the input file format), so I'd suggest you check that.

**Comment by zhangxiner2** [comment]
hello,I check my outfile and then find that the re_counts_iteration_1 and contig_links_scaled_iteration_1 have some error, like this:
$  head re_counts_iteration_1
utg005616l_pilon_pilon 0 0
utg001280l_pilon_pilon 0 0
utg004488l_pilon_pilon 0 0
utg001326l_pilon_pilon 0 0
utg003396l_pilon_pilon 0 0
utg005095l_pilon_pilon 0 0
utg003977l_pilon_pilon 0 0
utg000836l_pilon_pilon 0 0
utg000165l_pilon_pilon 0 0
utg004221l_pilon_pilon 0 0

$ head contig_links_scaled_iteration_1
utg000127l_pilon_pilon:B	utg003479l_pilon_pilon:B	0.0	1	0.0	8	False	False
utg001219l_pilon_pilon:E	utg004319l_pilon_pilon:E	0.0	1	0.0	2	False	False
utg000127l_pilon_pilon:B	utg003479l_pilon_pilon:E	0.0	1	0.0	14	False	False
utg000314l_pilon_pilon:E	utg001275l_pilon_pilon:B	0.0	1	0.0	2	False	False
utg001219l_pilon_pilon:E	utg004319l_pilon_pilon:B	0.0	1	0.0	2	False	False
utg001266l_pilon_pilon:B	utg001422l_pilon_pilon:E	0.0	1	0.0	1	False	False
utg001266l_pilon_pilon:B	utg001422l_pilon_pilon:B	0.0	1	0.0	2	False	False
utg000150l_pilon_pilon:E	utg003703l_pilon_pilon:E	0.0	1	0.0	5	False	False
utg003729l_pilon_pilon:E	utg004784l_pilon_pilon:E	0.0	1	0.0	4	False	False
utg000038l_pilon_pilon:E	utg001790l_pilon_pilon:B	0.0	1	0.0	65	False	False

I would appreciate it if you answer me as soon as possible.
Best 
Xin

**Comment by nadegeguiglielmoni** [comment]
I am not sure I understand what you mean by error? Your contig_links_scaled_iteration_1 does not strike me as weird. The 'False' is normal, it's just a boolean, I have it too in the files of a scaffolding that went fine. 
However, your re_counts_iteration_1 is definitely weird. This file is supposed to give the fragments of your genome after digestion by the restriction enzyme. Did you put the name of the enzyme as {AAGCTT} as you put in your first message? I think the problem comes from the use of {, and you should just put AAGCTT instead.

**Comment by machinegun** [comment]
I agree with @nadegeguiglielmoni. The issue is with `-e {AAGCTT}`. Please don't use curly braces and just specify enzyme as `-e AAGCTT`.
