### ISSUE TITLE
Final results are same when I used -m yes or no

### ISSUE THREAD

**Issue by wangxinbio** [machinegun/SALSA#58]
Hi 
When I use the -m yes and no, I found the result is same (FINAL.fasta and FINAL.agp).  Is this possible ? I tried two different data. Both got the same result for -m yes and -m no.

Thanks

**Comment by machinegun** [comment]
It depends upon the quality of the input assembly. If the input assembly is good enough that Hi-C couldn't break it, then using `-m` with either yes or no option would yield the same final result.
