### ISSUE TITLE
break_contigs.py  error

### ISSUE THREAD

**Issue by liufuyan2016** [machinegun/SALSA#6]
when I run the command :
python hi-c-scaffold-master/break_contigs.py -b breakpoints -a genome.fa -o final.assembly  -l contig_length_new
**Error occure as below** 
Traceback (most recent call last):
  File hi-c-scaffold-master/break_contigs.py", line 46, in <module>
    main()
  File "hi-c-scaffold-master/break_contigs.py", line 30, in main
    seq = id2seq[curr_contig]
**KeyError: '000003F_020|quiver'**
 Could you  help me?

**Comment by machinegun** [comment]
We are fixing this error. We should have an efficient and correct version of misassembly detection pushed soon. Meanwhile, you can run the pipeline with disabling an option to detect misassembly.

**Comment by liufuyan2016** [comment]
Thanks! When could you fix the bug? I want to use this function as soon as possible.

**Comment by machinegun** [comment]
We are working on some optimization parameters. Meanwhile, I can give a code that can plot the coverages for all contigs. With that, you can visually inspect if there is any mis-assembly. If you want that, give me your email id, I will send you instructions there.

**Comment by liufuyan2016** [comment]
Thanks for your help! My email is liufuyan2011@126.com

**Comment by liufuyan2016** [comment]
Could you sent a code that can plot the coverages for all contigs to me ?Thanks for your lot! My email is liufuyan2011@126.com

**Comment by peterdfields** [comment]
I'd be interested in the code for the plotting in order to determine the misassembly issue as well. peter.fields@unibas.ch

**Comment by mzhoufulai** [comment]
When will this bug be fixed？I have encountered the same problem.I hope the  correct version of misassembly detection will be pushed soon. Thanks.

**Comment by machinegun** [comment]
We have added the new SALSA pipeline to the master branch. It has the fixed version of misassembly detection and correction.
