### ISSUE TITLE
different result using iterative_salsa -vs- SALSA2

### ISSUE THREAD

**Issue by wangxinbio** [machinegun/SALSA#63]
Hi
When I used the older https://github.com/machinegun/SALSA/tree/iterative_salsa and SALSA2 (with -m no), I think they should get the same result. But I got a very different result. And the iterative_salsa is much better. What is the different between them ?
Thanks.

**Comment by machinegun** [comment]
We recommend using the latest version on the master branch. Iterative_salsa branch was used to develop new feature in SALSA2 and was experimental branch.
