### ISSUE TITLE
alignments_sorted.txt is empty

### ISSUE THREAD

**Issue by sisyyuan** [machinegun/SALSA#65]
Hi, I ran the convert.sh and got alignments.txt but the alignments_sorted.txt is empty. 
Commands:
#!/bin/bash
#PBS -l nodes=1:ppn=16,mem=125G
#BS -l walltime=8:00:00
#PBS -q copperhead
cd $PBS_O_WORKDIR
module load anaconda2
module load jdk/9.0.4
module load samtools

JUICER_JAR=/nobackup/zcsu_research/chicken/juicer_tools_1.10.10_jcuda0.8.jar
SALSA_OUT_DIR=/nobackup/zcsu_research/chicken/SALSA/scaffolds
SRIPT_PATH=/nobackup/zcsu_research/chicken/SALSA
samtools faidx ./scaffolds/scaffolds_FINAL.fasta
cut -f 1,2 ./scaffolds/scaffolds_FINAL.fasta.fai > ./scaffolds/chromosome_sizes.tsv
python alignments2txt.py -b ./scaffolds/alignment_iteration_1.bed  -a ./scaffolds/scaffolds_FINAL.agp -l ./scaffolds/scaffold_length_iteration_1 > ./scaffolds/alignments.txt
awk '{if ($2 > $6) {print $1"\t"$6"\t"$7"\t"$8"\t"$5"\t"$2"\t"$3"\t"$4} else {print}}'  ./scaffolds/alignments.txt | sort -k2,2d -k6,6d -T $PWD --parallel=16 | awk 'NF'  > ./scaffolds/alignments_sorted.txt

Instead, there are tons of sort******  files, like sort004exJ

Can you help to figure out what is wrong? Thanks!

**Comment by sisyyuan** [comment]
File is large, so sort creates intermediate results..

**Comment by Graystripe17** [comment]
Hi @sisyyuan Did you end up with a hic file? How did you solve the issue where alignments_sorted.txt is empty
