### ISSUE TITLE
Why networkx module < version 1.2, and how best to install?

### ISSUE THREAD

**Issue by SchwarzEM** [machinegun/SALSA#66]
SALSA2 requires networkx, but according to the documentation should *only* be run with a version of networkx that is quite old (less than version 1.2) and that therefore cannot be conveniently installed with conda (which is how many of us deal with the fussiness and fragility of Python-based software).

Is there any prospect that SALSA2 will begin to be usable with more modern versions of networkx?

If not, is there some efficient method of installing a local networkx module with a defined (old) version number, for somebody who is not root / superuser and who is not expert in Python?

I can find the software for version <1.2 networkx easily enough: https://networkx.github.io/documentation/networkx-1.1/

**Comment by machinegun** [comment]
You can install an appropriate version of networkx using virtual environment (https://virtualenv.pypa.io/en/latest/) . It doesn't require you to have root access.

**Comment by machinegun** [comment]
Closing this for now. Please let us know if you encounter any issues in future!
