### ISSUE TITLE
Does the argument "--iter X" have any real effect on SALSA2's behavior?

### ISSUE THREAD

**Issue by SchwarzEM** [machinegun/SALSA#68]
I've just tried running SALSA2 on the same three Hi-C data sets on three different genome assemblies, with the following arguments:

"--iter 3"
"--iter 7"
[no iter; let the program decide its own iteration number]

For all three data sets, the results come out exactly the same with all three arguments.  I have a hard time believing that that would really be happening if "--iter X' had any ability to change SALSA2's behavior.  What am I not understanding about this situation?

I should add that all three genome assemblies are third-generation (PacBio as the primary read set, assembled with Canu, polished with Quiver, then further polished with Illumina + Pilon), and the Hi-C data sets show abundant linkages between contigs even after following the Arima pipeline for removing artifacts.  There are six chromosomes in each genome.  A different Hi-C scaffolder (3D-DNA) is supposed to be able to assemble scaffolds for all six (though I have so far not been able to get that scaffolder to run in my own hands and give that result; it's not nearly as cleanly runnable as SALSA2).

Thanks for any advice on what, if anything, I should be doing differently!

**Comment by machinegun** [comment]
Yeah, the -i parameter doesn't have any effect. SALSA2 will figure out the number of iterations on it's own. We will remove that parameter in future versions.

**Comment by machinegun** [comment]
Closing for now. Please let us know if you have any further issues.
