### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by sangeet2019** [machinegun/SALSA#70]
Hello, I keep on getting "IndexError: list index out of range" error,

bedfile loaded
Starting Iteration 1
Traceback (most recent call last):
  File "/n/home00/slamichhaney/permananent_storage/Tools/SALSA/refactor_breaks.py", line 263, in <module>
    update_bed(scaffolds_new)
  File "/n/home00/slamichhaney/permananent_storage/Tools/SALSA/refactor_breaks.py", line 144, in update_bed
    first = prev_attrs[3].split('/')[1]
IndexError: list index out of range

### This is how my bed file looks (head example.bed)

scaffold_62367	129	279	A00121:89:HK3YWDSXX:2:1101:10004:12900	60	+
scaffold_8807	17423	17475	A00121:89:HK3YWDSXX:2:1101:10004:13401/1	60	-
scaffold_32766	8929	9079	A00121:89:HK3YWDSXX:2:1101:10004:13401/2	60	-
scaffold_2779	62687	62837	A00121:89:HK3YWDSXX:2:1101:10004:14215/1	60	+
scaffold_16848	1515	1614	A00121:89:HK3YWDSXX:2:1101:10004:14215/2	60	-
scaffold_9099	9442	9616	A00121:89:HK3YWDSXX:2:1101:10004:14246/1	60	-
scaffold_5874	16738	16791	A00121:89:HK3YWDSXX:2:1101:10004:14246/2	60	+
scaffold_61225	1623	1773	A00121:89:HK3YWDSXX:2:1101:10004:14528/1	60	+
scaffold_287	64581	64686	A00121:89:HK3YWDSXX:2:1101:10004:14528/2	60	-
scaffold_10981	9311	9461	A00121:89:HK3YWDSXX:2:1101:10004:17722	60	-

Any suggestions ?

**Comment by machinegun** [comment]
I think it's because your read names are inconsistent. Some of them have /1
or /2 to specify if its forward or reverse read and some don't. SALSA
requires  all the reads to have /1 or /2.

**Comment by sangeet2019** [comment]
Thanks a lot. I corrected the read names, and it ran after that.

But, now I am stuck in another issue. It is now showing up a key error as below. Any thoughts on this,

####
bedfile loaded
Starting Iteration 1
bedfile started
bedfile loaded
Loading Hi-C links 
Hybrid scaffold graph loaded, nodes = 163874 edges = 84234
Hi-C implied edges = 0
Traceback (most recent call last):
  File "/n/home00/slamichhaney/permananent_storage/Tools/SALSA/get_seq.py", line 96, in <module>
    curr_contig += revcompl(id2seq[curr[0]])
  File "/n/home00/slamichhaney/permananent_storage/Tools/SALSA/get_seq.py", line 31, in <lambda>
    revcompl = lambda x: ''.join([{'A':'T','B':'N','C':'G','G':'C','T':'A','N':'N','R':'N','M':'N','Y':'N','S':'N','W':'N','K':'N','a':'t','c':'g','g':'c','t':'a','n':'n',' ':'',}[B] for B in x][::-1])
KeyError: 'H'
####

**Comment by machinegun** [comment]
Hi,

It appears that your input contig FASTA file has 'H' in one of the sequences (not the headers). Can you please check if this is the case?

**Comment by machinegun** [comment]
Closing this for now. Please let us know if you encounter any further issues.
