### ISSUE TITLE
how to calculate the score value for contig length shorter than 300,000bp?

### ISSUE THREAD

**Issue by liufuyan2016** [machinegun/SALSA#8]
In the scripts :new_links.py  ,there are two assignments：l1 = 300000.0  l2 = 300000.0；if my contig length  short than 300,000bp, does the l1 and  l2 value is meaningful？

if prev_attrs[0] != attrs[0]:
                    prev_read = prev_attrs[3]
                    curr_read = attrs[3]
                    #print prev_read.split('/')[0]
                    if prev_read.split('/')[0] == curr_read.split('/')[0]:
                        #print 'here'
                        pos1 = (long(prev_attrs[1]) + long(prev_attrs[2]))/2.0
                        pos2 = (long(attrs[1]) + long(attrs[2]))/2.0
                        **l1 = 300000.0
                        l2 = 300000.0**
                       
                        first = ''
                        second = ''
                        if prev_attrs[0] < attrs[0]:
                            first = prev_attrs[0]
                            second = attrs[0]
                        else:
                            first = attrs[0]
                            second = prev_attrs[0]
                            pos1,pos2 = pos2, pos1

**Comment by machinegun** [comment]
You can change these values to whatever that suit your data.

**Comment by liufuyan2016** [comment]
But when my contig length is shorter than this value,the r1 and r2 value is much larger than real value,and larger than 1, so the norm_score will be larger than real value too.This calculation will be error for these shorter contigs. In other word, this soft only useful for these contigs length larger than the l1 and l2 values 
r1 = l1 / len1
r2 = l2 / len2

**Comment by machinegun** [comment]
You can set r1 =len1/3 and r2=len2/3. It should work after this setting.
